# Generated by Django 5.1.4 on 2026-06-05 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(upload_to='airplanes/', verbose_name='Фото')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за час')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Самолёт',
                'verbose_name_plural': 'Самолёты',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField(verbose_name='Дата вылета')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='flights.airplane')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-departure_date'],
            },
        ),
    ]
